#!/bin/sh
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}
me=$(realpath $0)
program=$(basename $me)
installation=$(dirname $me)
executable=$installation/opt/arangodb/bin/$program
if [ -x "$executable" ] ; then
  case $1 in
    abort|auth|create|help|remove|retry|start|stop|upgrade|version)
      exec "$executable" "$@"
      ;;
    *)
      exec "$executable" --server.arangod="$installation/opt/arangodb/sbin/arangod" --server.js-dir="$installation/opt/arangodb/share/arangodb3/js" "$@"
      ;;
  esac
fi
echo "Could not find executable ${executable}!"
exit 1
