#!/bin/bash
chown -R root:root /root/.gnupg
chmod 700 /root/.gnupg

if test -d /root/.gnupg-old; then
  chown -R root:root /root/.gnupg-old
  chmod 700 /root/.gnupg-old
fi

editions="Community Enteprise"
if [ -n "$1" ] && [ "$1" = "Enterprise" ]; then
  echo "\$1 positional parameter is present: making only $1 repo(s)!"
  editions="Enterprise"
fi

script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/createRepo"

oskar_dir="$script_dir/.."

echo "run test"

echo "=== gpg ==="
gpg --version

echo "=== RPM ==="
rpm --version

version="$ARANGODB_VERSION"
incoming="/packages"
repo="/repositories"

test -n "$version" || exit 1

echo "USE_ARM=$USE_ARM"

#centos
#fedora
#suse
for edition in $editions
do
  mkdir -p $repo/$edition/RPM/x86_64
  if [[ "$USE_ARM" = "On" ]]
  then
    mkdir -p $repo/$edition/RPM/aarch64
  fi
done

arch_list="x86_64"
[[ "$USE_ARM" = "On" ]] && arch_list="$arch_list:aarch64"

echo "User archs are $arch_list"

ensure_oskar "$version" "$incoming" "$repo" \
            "Linux" "RPM" \
            "$arch_list" "rpm"

#debian
#ubuntu
for edition in $editions
do
  mkdir -p $repo/$edition/Debian/amd64
  if [[ "$USE_ARM" = "On" ]]
  then
    mkdir -p $repo/$edition/Debian/arm64
  fi
done

arch_list="amd64"
[[ "$USE_ARM" = "On" ]] && arch_list="$arch_list:arm64"

echo "User archs are $arch_list"

ensure_oskar "$version" "$incoming" "$repo" \
            "Linux" "Debian" \
            "$arch_list" "deb" $([[ " $editions " == *" Community "* ]] && echo "true" || echo "false")

chown -R $UID.$GID $repo

for edition in $editions
do
  cd $repo/$edition/Debian
  if test -d /root/.gnupg-old; then
    gpg2 --homedir /root/.gnupg-old --no-permission-warning --armor --export info@arangodb.com  > Release.key
  else
    gpg2 --no-permission-warning --armor --export admin@arangodb.com  > Release.key
  fi
done
