#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/createRepo"

oskar_dir="$script_dir/.."

echo "run test"

version="$ARANGODB_PACKAGES"
incoming="/packages"
repo="/repositories"

test -n "$version" || exit 1

#centos
#fedora
#suse
mkdir -p $repo/Community/RPM/x86_64
mkdir -p $repo/Enterprise/RPM/x86_64

ensure_oskar "$version" "$incoming" "$repo" \
            "Linux" "RPM" \
            "x86_64" "rpm"

#debian
#ubuntu
mkdir -p $repo/Community/Debian/amd64
mkdir -p $repo/Enterprise/Debian/amd64

ensure_oskar "$version" "$incoming" "$repo" \
            "Linux" "Debian" \
            "amd64" "deb"

chown -R $UID.$GID $repo

cd $repo/Community/Debian
gpg2 --no-permission-warning --armor --export info@arangodb.com  > Release.key

cd $repo/Enterprise/Debian
gpg2 --no-permission-warning --armor --export info@arangodb.com  > Release.key
