#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/lib/oskar.bash" || exit 1

debSign(){
    local file="$1"
    asc="$file.asc"
    if test -s "$asc" -a "$asc" -nt "$file";  then
        echo "using old $asc file"
    else
        echo "signing file $file"
        rm -f "$asc"

        local gpg_dir=/root/.gnupg-old
        if ! test -d /root/.gnupg-old; then
          gpg_dir=/root/.gnupg
        fi

        if gpg2 --homedir $gpg_dir --no-permission-warning --pinentry-mode=loopback --digest-algo SHA512 --passphrase-fd 0 --armor --detach-sign -u "$KEYNAME" "$file" <<<"$ARANGO_SIGN_PASSWD"; then
            return 0
        else
            echo "retry"
            setup_gpg
            file="$1"
            gpg2 --homedir $gpg_dir --no-permission-warning --pinentry-mode=loopback --digest-algo SHA512 --passphrase-fd 0 --armor --detach-sign -u "$KEYNAME" "$file" <<<"$ARANGO_SIGN_PASSWD"
        fi
    fi
    return $?
}

debSign "$@"
exit $?


# backwards compatibility for docker builds:
# gpg2 --armor --export info@arangodb.com  > Release.key
